name: property_crm
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # STATE MANAGEMENT
  get: ^4.6.5
  get_storage: ^2.1.1

  # IMAGE
  flutter_svg: ^2.0.7

  # CONNECTION
  connectivity_plus: ^4.0.1

  # PERMISSION HANDLER
  permission_handler: ^10.4.3

  # OTP FIELD
  pin_code_fields: ^7.4.0

  # INDICATOR
  smooth_page_indicator: ^1.1.0
  loading_indicator: ^3.1.1

  # FIREBASE
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
#  firebase_messaging: ^14.6.5
#  flutter_local_notifications: ^15.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900